### ISSUE TITLE
Ignores hidden files

### ISSUE THREAD

**Issue by willdashwood** [whattheserver/cyberpanel-fixperms#1]
Hello,

Glad to see a fork of a script I always use on cPanel servers! Seems to work great but I noticed the ownership of hidden files weren't changed from root to the account owner in question.It seems to set permissions OK.

Thanks!

**Comment by meramsey** [comment]
if you can provide an example of where I can see this and a suggestion of what you think would fix it id be happy to look into a fix. unfortunately not sure what paths the files in question are located to know if they should have been fixed.

The logic for the script only fixes the below paths.

$HOMEDIR"/public_html
$HOMEDIR/logs

If not running this as root chowning files from root to another user will not work unless it has elevated sudo like perms.

Please provide more information and example and I'll take a look when i can.

**Comment by meramsey** [comment]
@willdashwood 

After researching some I think i might see possibly one edge case which you are referring to.
I made a custom version which might work for testing here:
https://github.com/whattheserver/cyberpanel-fixperms/raw/836bb53be5508976bd579c115db828b053956830/fixperms.sh

If this works please let me know ill merge into the main stable branch

Thanks for reporting as well. Always happy to improve things.

**Comment by willdashwood** [comment]
Sorry for the delay. Yes that version seemed to fix it! Thanks!

**Comment by meramsey** [comment]
Sweet thanks for the confirmation. Merged into main and closing this now. :)
