### ISSUE TITLE
Chown Problem 

### ISSUE THREAD

**Issue by ZgrK** [whattheserver/cyberpanel-fixperms#4]
https://github.com/whattheserver/cyberpanel-fixperms/blob/7b6e5a792d992c92a3adb6596b91e6d1da5216cf/fixperms.sh#L112

Because this .[^.]* only accept hidden file I guess you guys test something :) 

I fix this in #5

**Comment by meramsey** [comment]
Can you advise how we can reproduce the issue you feel warrants this change? 

That code matches both hidden that start with . and normal files. For context see the below original issue opened where we implemented this fix. 


https://github.com/whattheserver/cyberpanel-fixperms/issues/1

If you can provide how we can reproduce and test the issue and how your proposal addresses your issue without introducing other issues I'll be happy to merge

**Comment by ZgrK** [comment]
With this .[^.]* only choose Hidden files.

I debug like this `find .[^.]* ` 

**Result**
.htaccess
.htaccess.bk

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**Comment by meramsey** [comment]
Ah when viewing on mobile i missed it was adding to and not replacing the previous line. I apologize after viewing and running some more tests I see what your referring too now.

Merge request has been merged.
