### ISSUE TITLE
Error with the latest cyberpanel version.

### ISSUE THREAD

**Issue by vdominik17** [whattheserver/cyberpanel-fixperms#8]
Hi!

In ubuntu 20.04 with 2.3 version of the cyberpanel i get that error:
`./fixperms.sh: 176: [[: not found
./fixperms.sh: 184: [[: not found`

Please solve that. :/

**Comment by meramsey** [comment]
it sounds like script possibly is being excuted via sh and the evaluation is failing vs using bash like this
https://superuser.com/questions/374406/why-do-i-get-not-found-when-running-a-script

I went ahead and updated the script shebang to handle things better and the readme as well so give latest version a try and let me know if it works when run via bash

if your still having issues with latest
please run the script with `bash -x fixperms.sh` so it shows what is happening

**Comment by vdominik17** [comment]
Hi!

Thanks for the fast reply, and help.

Now works like charm, your script saved our hosting, one of the sysadmin of mine is fucked up the group permissions.. :D 

Thats solved that problem.

Nice script.
